Redirect error messages to stderr Add some debugging info to help track down nightly test failures
git-svn-id: svn://svn.code.sf.net/p/x10/code@2480 a326200e-df2c-42e0-81fa-597e909af41d

diff --git a/trunk/x10.common/bin/testScript0 b/trunk/x10.common/bin/testScript0
--- a/trunk/x10.common/bin/testScript0
+++ b/trunk/x10.common/bin/testScript0
@@ -16,7 +16,7 @@ chkArgs() {
 local num="$1"
 shift
 if [[ $# -ne $num ]]; then
-	echo "Argument count error, expecting $num, found $#"
+	echo >&2 "Argument count error, expecting $num, found $#"
 	exit 1
 fi
 }
@@ -25,7 +25,7 @@ usage() {
 # print usage message and exit with nonzero return code
 chkArgs 0 "$@"
 
-echo "
+echo >&2 "
 Usage:
 
 testScript [-clean] [-cleanOnly] [-f] [-t timeLimit] [-shiftLog] [ -m userEmail]
@@ -131,7 +131,7 @@ chkArgs 1 "$@"
     if ! "$tool" --version &> /dev/null; then
       TOOL=`type -p $tool`
       [ -n "$TOOL" ] && TOOLLOC="; $tool is $TOOL"
-      echo "Cannot find GNU $tool in the PATH$TOOLLOC"
+      echo >&2 "Cannot find GNU $tool in the PATH$TOOLLOC"
       exit 2
     fi
 }
@@ -191,16 +191,16 @@ checkUsage() {
       x10lib="$2"
       shift 2
     elif [[ "$1" = -* ]]; then
-      echo "unrecognized flag $1, or missing argument"
+      echo >&2 "unrecognized flag $1, or missing argument"
       usage
     else
-      echo "extraneous argument $1"
+      echo >&2 "extraneous argument $1"
       usage
     fi
   done
   if [[ ! -e .ThisIsAnX10TestDirectory && -z "$force" ]] ; then
-    echo "You must be in an X10 test directory to run this script"
-    echo "The file .ThisIsAnX10TestDirectory must be present"
+    echo >&2 "You must be in an X10 test directory to run this script"
+    echo >&2 "The file .ThisIsAnX10TestDirectory must be present"
     usage
   fi
 
@@ -299,6 +299,7 @@ genTest() {
   #for f in `eval "find $findpat -type f -name '*.x10' -print"`; do
   #TESTS="`eval "find '$topDir' -type f -name '*.x10' $findpat -print"`"
   TESTS="`eval "find $findpat -type d -name CVS -prune -o -type f -name '*.x10' -print"`"
+  echo 2>&1 "Running tests: $TESTS"
   while read f; do
     file="${f##*/}"    # if f is a/b/c file will be c
     path="${f%/$file}" # if f is a/b/c path will be a/b
@@ -310,6 +311,7 @@ genTest() {
       path="${path%/$pkg}"
       [ -n "$pkg" ] || pkg='.'
       doTest "$pkg" "$path" "${file%.x10}" # run an actual x10 test case
+      echo 2>&1 "Done with $path/$pkg/$file"
     fi
   done <<<"$TESTS"
   return 0
