Check for GNU utils before proceeding
git-svn-id: svn://svn.code.sf.net/p/x10/code@2288 a326200e-df2c-42e0-81fa-597e909af41d

diff --git a/trunk/x10.common/bin/testScript0 b/trunk/x10.common/bin/testScript0
--- a/trunk/x10.common/bin/testScript0
+++ b/trunk/x10.common/bin/testScript0
@@ -126,9 +126,25 @@ exit 1
 
 }
 
+checkGNU() {
+# check whether a particular tool is from GNU or exit with nonzero return code
+chkArgs 1 "$@"
+
+    local tool="$1"
+
+    if ! "$tool" --version &> /dev/null; then
+      echo "Cannot find GNU $tool in the PATH"
+      exit 2
+    fi
+}
+
 checkUsage() {
 # Process the arguments.
 # Also perform simple checks before running script.
+
+  checkGNU egrep
+  checkGNU find
+  checkGNU sed
 
   timeLimit=60
   mailDest=""
