Detect compile time exception failures for _MustFailCompile test cases in c++ backend.
git-svn-id: svn://svn.code.sf.net/p/x10/code/trunk@15380 a326200e-df2c-42e0-81fa-597e909af41d

diff --git a/x10.tests/bin/xtestScriptCT++ b/x10.tests/bin/xtestScriptCT++
--- a/x10.tests/bin/xtestScriptCT++
+++ b/x10.tests/bin/xtestScriptCT++
@@ -698,12 +698,22 @@ function main {
 		cat ${tccompdat} 1>&2
 		if [[ $rc != 0 && "$tcvcode" == "FAIL_COMPILE" ]]; then
 			let 'tcfcompcnt += 1'
-			let 'tcpasscnt += 1'
-			printf " *** Y ***"
-			__cat_test_result_explanation="${className} met expectation: MustFailCompile."
-			__cat_test_result="SUCCESS"
 			__cat_test_exit_code=$rc
-			printf "\n****** $tDir $className succeeded.\n" >> $tccompdat
+            ${EGREP} "Exception in thread" $tccompdat >/dev/null 2>&1
+            if [[ $? == 0 ]]; then
+                printf " *** X ***"
+                let 'tcfailcnt += 1'
+                printf "\n[$prog: err]: compile time exception for ${className}\n"
+                __cat_test_result_explanation="${className} did not meet expectation: expected=MustFailCompile actual=FailCompileWithException (exception in thread main)."
+                __cat_test_result="FAILURE"
+                printf "\n****** $tDir $className failed: compile time exception\n" >> $tccompdat
+            else
+			    printf " *** Y ***"
+			    let 'tcpasscnt += 1'
+			    __cat_test_result_explanation="${className} met expectation: MustFailCompile."
+			    __cat_test_result="SUCCESS"
+			    printf "\n****** $tDir $className succeeded.\n" >> $tccompdat
+            fi
 			xmlLog $tccompdat
 			continue
 		elif [[ $rc == 0 && "$tcvcode" == "FAIL_COMPILE" ]]; then
