hack to grab a r2571 of polyglot for nightly tests because things are still broken.
git-svn-id: svn://svn.code.sf.net/p/x10/code@10992 a326200e-df2c-42e0-81fa-597e909af41d

diff --git a/trunk/x10.tests/bin/buildScriptCT++ b/trunk/x10.tests/bin/buildScriptCT++
--- a/trunk/x10.tests/bin/buildScriptCT++
+++ b/trunk/x10.tests/bin/buildScriptCT++
@@ -6,6 +6,38 @@
 # $Id$
 # Script that sources and builds all components required for regression.
 
+svnUpdatePolyglotHack() {
+	if [[ ! -d $1 ]]; then
+		( \
+			cd $(dirname $1); \
+			printf "\n## [$prog]: checking out module $(basename $1)...\n"; \
+			svn co -r2571 "${2}/$(basename $1)"; \
+			exit $?; \
+		)
+		if (( $? != 0 )); then
+			printf "\n[$prog: err]: checkout failed for module $(basename $1)\n"
+			return 1
+		else
+			printf "\n## done.\n"
+			return 0
+		fi
+	else
+		( \
+			cd $1; \
+			printf "\n## [$prog]: updating module $(basename $1)...\n"; \
+			svn update -r2571; \
+			exit $?; \
+		)
+		if (( $? != 0 )); then
+			printf "\n[$prog: err]: update failed for module $(basename $1)\n"
+			return 1
+		else
+			printf "\n## done.\n"
+			return 0
+		fi
+	fi
+}
+
 svnUpdate() {
 	if [[ ! -d $1 ]]; then
 		( \
@@ -127,7 +159,7 @@ main() {
 	if [[ -d $POLYGLOT_HOME ]]; then
 		rm -rf $POLYGLOT_HOME
 	fi
-	svnUpdate $POLYGLOT_HOME $POLYGLOT_SVNROOT
+	svnUpdatePolyglotHack $POLYGLOT_HOME $POLYGLOT_SVNROOT
 	status=$?
 	if (( $status != 0 )); then
 		return $status
