x10c++ regression scripts with cattrack support. * driverScriptCT++ buildScriptCT++ xtestScriptCT++ Scripts without CT suffix are plain -- without xml generation.
git-svn-id: svn://svn.code.sf.net/p/x10/code@8187 a326200e-df2c-42e0-81fa-597e909af41d

diff --git a/trunk/x10.tests/bin/xtestScriptCT++ b/trunk/x10.tests/bin/xtestScriptCT++
--- a/trunk/x10.tests/bin/xtestScriptCT++
+++ b/trunk/x10.tests/bin/xtestScriptCT++
@@ -109,7 +109,7 @@ function printUsage {
 		printf -- "-h | -help\n"
 		printf "  Print this help message.\n\n"
 	fi
-	cleanUpExit $1
+	cleanUpExitHarness $1
 }
 
 # parse command line options and arguments
@@ -138,14 +138,14 @@ function parseCmdLine {
 		elif [[ "$1" == "-logPath" && $# -ge 2 ]]; then
 			if [[ ! -d "$2" ]]; then
 				printf "\n[${prog}: err]: Log directory $2 must exist\n"
-				cleanUpExit 1
+				cleanUpExitHarness 1
 			fi
 			tclogpath=$2
 			shift 2
 		elif [[ "$1" == "-listFile" && $# -ge 2 ]]; then
 			if [[ ! -r "$2" ]]; then
 				printf "\n[${prog}: err]: List file $2 must exist & be readable\n"
-				cleanUpExit 1
+				cleanUpExitHarness 1
 			fi
 			tcpatfile=$2
 			shift 2
@@ -204,7 +204,19 @@ function parseCmdLine {
 # generate list of tests for the specified pattern(s)
 # usage: findTests testpat(s)
 function findTests {
-	eval "find $1 -type d -name '.svn' -prune -o -type f -name '*.x10' -print"
+	local testPat="$1"
+	local findpat=""
+	local dirlist
+
+	#eval "find $1 -type d -name '.svn' -prune -o -type f -name '*.x10' -print"
+	if [[ -n "$testPat" && "${testPat}" != "." ]]; then
+		#findpat="$(printf "%q " "${testPat}" | sed 's/\\\\\([\*\?]\)/\1/g')"
+		eval "find $testPat -type d -name '.svn' -prune -o -type f '(' -name '*.x10' -o -name '*.fwd' ')' -print | sort"
+	else
+		dirlist="$(eval "find -type d -name '.svn' -prune -o -type d -name '*' -print | sort")"
+		dirlist="$(echo $dirlist | tr '\n' ' ')"
+		eval "find $dirlist -maxdepth 1 -type f '(' -name '*.x10' -o -name '*.fwd' ')' -print"
+	fi
 }
 
 # check whether the specified test case file is valid
@@ -317,8 +329,8 @@ tctmpdir=${TMPDIR}/${prog}.$$.${tctimestamp}
 mkdir -p $tctmpdir
 
 # cleanup & exit if aborted
-# usage: cleanUpExit excode
-function cleanUpExit {
+# usage: cleanUpExitHarness excode
+function cleanUpExitHarness {
 	if [[ -d ${tctmpdir} ]]; then
 		if [[ -f ${tctmprlog} && ! -z ${tcrlogfile} ]]; then
 			if [[ ! -d ${tclogpath} ]]; then
@@ -339,10 +351,10 @@ function cleanUpExit {
 }
 
 # exit gracefully upon receiving these signals
-trap 'cleanUpExit 1' INT QUIT TERM
+trap 'cleanUpExitHarness 1' INT QUIT TERM
 
 # default values
-DEFAULT_TIMEOUT=60
+DEFAULT_TIMEOUT=120
 DEFAULT_LOGPATH="log"
 DEFAULT_NPLACES=1
 
@@ -368,7 +380,7 @@ typeset -i tctimeout=1
 
 # default timeout value, if timeout is enabled
 typeset -i tctoutval=$DEFAULT_TIMEOUT
-typeset -i tccomptout=360
+typeset -i tccomptout=420
 # run tests even if the script is launched in a non-test dir
 # default: no
 typeset -i tcforce=0
@@ -454,12 +466,65 @@ function init {
 	# exit code: 1
 	if [[ $tcforce != 1 && ! -e .ThisIsAnX10TestDirectory ]]; then
 		printf "\n[$prog: err]: $(basename $(pwd)) not a valid X10 launch dir\n"
-		cleanUpExit 1
+		cleanUpExitHarness 1
 	fi
 
 	# set final log destination(s)
 	tcrlogfile=${tclogpath}/${prog}.run.${tctimestamp}.log
 	tcelogfile=${tclogpath}/${prog}.err.${tctimestamp}.log
+}
+
+function xmlLog {
+	__cat_test_end_time=$(perl -e 'print time;')
+	let '__cat_test_duration = __cat_test_end_time - __cat_test_start_time'
+	if [[ "${__cat_current_group}" != ${__cat_opened_group} ]]; then
+		if [[ "${__cat_opened_group}" != "invalid" ]]; then
+			printf "</group>\n\n" >> $TLOGF
+		fi
+		printf "<group>\n" >> $TLOGF
+		printf "\t<name>${__cat_current_group}</name>\n" >> $TLOGF
+		__cat_opened_group="${__cat_current_group}"
+	fi
+	printf "\n\t<test>\n" >> $TLOGF
+	printf "\t\t<name>${__cat_test_name}</name>\n" >> $TLOGF
+	printf "\t\t<command>\n" >> $TLOGF
+	printf "## compilation:\n" >> $TLOGF
+	echo "${__cat_test_x10c_command}" | sed -e 's/</\&lt;/g' \
+		-e 's/>/\&gt;/g' \
+		-e 's/&&/\&amp;\&amp;/g' \
+		-e 's/ & / \&amp; /g' >> $TLOGF
+	printf "\n\n" >> $TLOGF
+	printf "## execution:\n" >> $TLOGF
+	echo "${__cat_test_x10_command}" | sed -e 's/</\&lt;/g' \
+		-e 's/>/\&gt;/g' \
+		-e 's/&&/\&amp;\&amp;/g' \
+		-e 's/ & / \&amp; /g' >> $TLOGF
+	printf "\n\n" >> $TLOGF
+	printf "\t\t</command>\n" >> $TLOGF
+	printf "\t\t<parameters>\n" >> $TLOGF
+	printf "\t\t\t<parameter key=\"x10c.sourcepath\" value=\"${__cat_test_x10c_sourcepath}\"/>\n" >> $TLOGF
+	printf "\t\t\t<parameter key=\"x10c.classpath\" value=\"${__cat_test_x10c_classpath}\"/>\n" >> $TLOGF
+	printf "\t\t\t<parameter key=\"x10c.directory\" value=\"${__cat_test_x10c_directory}\"/>\n" >> $TLOGF
+	printf "\t\t\t<parameter key=\"x10.classpath\" value=\"${__cat_test_x10_classpath}\"/>\n" >> $TLOGF
+	printf "\t\t\t<parameter key=\"x10.timeout\" value=\"${__cat_test_x10_timeout}\"/>\n" >> $TLOGF
+	printf "\t\t</parameters>\n" >> $TLOGF
+	printf "\t\t<test-execution>\n" >> $TLOGF
+	printf "\t\t\t<name>default</name>\n" >> $TLOGF
+	printf "\t\t\t<exit-code>${__cat_test_exit_code}</exit-code>\n" >> $TLOGF
+	printf "\t\t\t<duration>${__cat_test_duration}</duration>\n" >> $TLOGF
+	printf "\t\t\t<result>${__cat_test_result}</result>\n" >> $TLOGF
+	printf "\t\t\t<result-explanation>${__cat_test_result_explanation}</result-explanation>\n" >> $TLOGF
+	printf "\t\t\t<statistics/>\n" >> $TLOGF
+	printf "\t\t\t<output>\n" >> $TLOGF
+	sed -e 's/</\&lt;/g' \
+		-e 's/>/\&gt;/g' \
+		-e 's/&&/\&amp;\&amp;/g' \
+		-e 's/ & / \&amp; /g' \
+		-e '/Unexpected character ignored:/d' \
+		$1 >> $TLOGF
+	printf "\t\t\t</output>\n" >> $TLOGF
+	printf "\t\t</test-execution>\n" >> $TLOGF
+	printf "\t</test>\n" >> $TLOGF
 }
 
 # main routine that invokes the rest
@@ -485,12 +550,12 @@ function main {
 	fi
 	if [[ ! -f $X10CPP ]]; then
 		printf "\n[$prog: err]: unable to locate x10c++ compiler!\n"
-		cleanUpExit 2
+		cleanUpExitHarness 2
 	fi
 	RUNX10=$(dirname $X10CPP)/runx10
 	if [[ ! -f $RUNX10 ]]; then
 		printf "\n[$prog: err]: unable to locate runx10 command!\n"
-		cleanUpExit 2
+		cleanUpExitHarness 2
 	fi
 
 	X10LIB=$X10LIB
@@ -499,11 +564,11 @@ function main {
 	fi
 	if [[ ! -f $X10LIB/include/x10/x10.h ]]; then
 		printf "\n[$prog: err]: unable to locate pgas header files!\n"
-		cleanUpExit 2
+		cleanUpExitHarness 2
 	fi
 	if [[ ! (-f $X10LIB/lib/libupcrts_lapi.a || -f $X10LIB/lib/libupcrts_sockets.a || -f $X10LIB/lib/libupcrts_smp.a) ]]; then
 		printf "\n[$prog: err]: unable to locate pgas libraries!\n"
-		cleanUpExit 2
+		cleanUpExitHarness 2
 	fi
 
 	X10LANG=$X10LANG
@@ -512,11 +577,11 @@ function main {
 	fi
 	if [[ ! (-f $X10LANG/x10rt17.h || -f $X10LANG/include/x10rt17.h) ]]; then
 		printf "\n[$prog: err]: unable to locate x10rt header files!\n"
-		cleanUpExit 2
+		cleanUpExitHarness 2
 	fi
 	if [[ ! (-f $X10LANG/libx10rt17.a || -f $X10LANG/lib/libx10rt17.a) ]]; then
 		printf "\n[$prog: err]: unable to locate x10rt libraries!\n"
-		cleanUpExit 2
+		cleanUpExitHarness 2
 	fi
 
 	# prepare test case list
@@ -526,7 +591,7 @@ function main {
 	declare -a tclist=($(findTests '$tcpatlist'))
 	if [[ ${#tclist[*]} == 0 ]]; then
 		printf "\n[$prog: err]: zero tests found under $(basename $(pwd))\n"
-		cleanUpExit 3
+		cleanUpExitHarness 3
 	fi
 	printf "\n===> ${tclist[*]}\n\n"
 	tctotalcnt=${#tclist[*]}
@@ -559,8 +624,15 @@ function main {
 		fi
 		let 'tcvalidcnt += 1'
 
+		__cat_test_start_time=$(perl -e 'print time;')
+
 		# create the test root
 		tctarget=$(basename $tc | sed -e 's;.x10;;')
+		__cat_test_name="$className"
+		local testDir=$(dirname $tc)
+		local tDir=${testDir#\.\/}
+		tDir=`echo "$testDir" | sed -e 's/\//\./g'`
+		__cat_current_group="$tDir"
 		if [[ -d ${tcroot} ]]; then
 			rm -rf ${tcroot}
 		fi
@@ -580,8 +652,12 @@ function main {
 		else
 			extendList=""
 		fi
+		__cat_test_x10c_sourcepath="$tcroot"
+		__cat_test_x10c_classpath="${EXTRA_CLASSPATH}"
+		__cat_test_x10c_directory="$testDir"
 		comp_cmd="${X10CPP} -t -v -commandlineonly -MAIN_CLASS=$tctarget -sourcepath $tcroot -d $tcroot $tc $extendList ${X10TEST_PATH}/x10lib/harness/x10Test.x10"
 		tccompdat=${tcroot}/${tctarget}.comp
+		__cat_test_x10c_command="$(echo execTimeOut $tccomptout $tccompdat \"${comp_cmd}\")"
 		execTimeOut $tccomptout $tccompdat "${comp_cmd}"
 		rc=$?
 		cat ${tccompdat} 1>&2
@@ -589,18 +665,30 @@ function main {
 			let 'tcfcompcnt += 1'
 			let 'tcpasscnt += 1'
 			printf " *** Y ***"
+			__cat_test_result_explanation="${tctarget} met expectation: MustFailCompile."
+			__cat_test_result="SUCCESS"
+			__cat_test_exit_code=$rc
+			xmlLog $tccompdat
 			continue
 		elif [[ $rc == 0 && "$tcvcode" == "FAIL_COMPILE" ]]; then
 			printf " *** X ***"
 			let 'tcfvcodecnt += 1'
 			let 'tcfailcnt += 1'
 			printf "\n[$prog: err]: invalid validation code for ${tctarget}\n"
+			__cat_test_result_explanation="${tctarget} did not meet expectation: expected=MustFailCompile actual=Succeed (invalid validation code)."
+			__cat_test_result="FAILURE"
+			__cat_test_exit_code=42
+			xmlLog $tccompdat
 			continue
 		elif [[ $rc != 0 && "$tcvcode" != "FAIL_COMPILE" ]]; then
 			let 'tcfcompcnt += 1'
 			let 'tcfailcnt += 1'
 			printf " *** X ***"
 			printf "\n[$prog: err]: can't generate c++ sources for ${tctarget}\n"
+			__cat_test_result_explanation="${tctarget} did not meet expectation: expected=Succeed actual=FailCompile (failed to generate c++ sources)."
+			__cat_test_result="FAILURE"
+			__cat_test_exit_code=$rc
+			xmlLog $tccompdat
 			continue
 		fi
 		let 'tccompcnt += 1'
@@ -618,6 +706,13 @@ function main {
 
 		# the actual output will be logged here
 		tcoutdat=${tcroot}/${tctarget}.out
+		__cat_test_x10_classpath="$EXTRA_CLASSPATH"
+		__cat_test_x10_timeout="$tctoutval"
+		if [[ $tctimeout == 0 ]]; then
+			__cat_test_x10_command="$(echo $run_cmd > $tcoutdat)"
+		else
+			__cat_test_x10_command="$(echo execTimeOut $tctoutval $tcoutdat \"${run_cmd}\")"
+		fi
 		printf " ++ E [EXECUTION]"
 		( \
 			printf "\n===> cd $tcroot\n" 1>&2; \
@@ -637,6 +732,10 @@ function main {
 			printf "\n<<==========OUTPUT=======\n"
 			cat ${tcoutdat}
 			printf "=======================>>\n"
+			__cat_test_result_explanation="${tctarget} met expectation: Succeed."
+			__cat_test_result="SUCCESS"
+			__cat_test_exit_code=$rc
+			xmlLog $tcoutdat
 			continue
 		fi
 		if [[ $tctimeout == 0 ]]; then
@@ -645,23 +744,39 @@ function main {
 				let 'tcfexeccnt += 1'
 				printf " *** X ***"
 				printf "\n[$prog: err]: failed to execute ${tctarget}\n"
+				__cat_test_result_explanation="${tctarget} did not meet expectation: expected=Succeed actual=FailRun."
+				__cat_test_result="FAILURE"
+				__cat_test_exit_code=$rc
+				xmlLog $tcoutdat
 				continue
 			elif [[ $rc == 0 && $tcvcode == "FAIL_RUN" ]]; then
 				printf " *** X ***"
 				let 'tcfailcnt += 1'
 				let 'tcfvcodecnt += 1'
 				printf "\n[$prog: err]: invalid validation code for ${tctarget}\n"
+				__cat_test_result_explanation="${tctarget} did not meet expectation: expected=MustFailRun actual=Succeed (invalid validation code)."
+				__cat_test_result="FAILURE"
+				__cat_test_exit_code=42
+				xmlLog $tcoutdat
 				continue
 			elif [[ $rc > 0 && $tcvcode == "FAIL_RUN" ]]; then
 				printf " *** Y ***"
 				let 'tcfexeccnt += 1'
 				let 'tcpasscnt += 1'
+				__cat_test_result_explanation="${tctarget} met expectation: MustFailRun."
+				__cat_test_result="SUCCESS"
+				__cat_test_exit_code=0
+				xmlLog $tcoutdat
 				continue
 			else
 				printf " *** X ***"
 				let 'tcfailcnt += 1'
 				let 'tcfvcodecnt += 1'
 				printf "\n[$prog: err]: invalid validation code ${tctarget}\n"
+				__cat_test_result_explanation="${tctarget} did not meet expectation: expected=Succeed actual=FailRun (invalid validation code)."
+				__cat_test_result="FAILURE"
+				__cat_test_exit_code=42
+				xmlLog $tcoutdat
 				continue
 			fi
 		else
@@ -671,18 +786,30 @@ function main {
 				let 'tcftoutcnt += 1'
 				let 'tcfexeccnt += 1'
 				printf "\n[$prog: err]: ${tctarget} is killed due to timeout\n"
+				__cat_test_result_explanation="${tctarget} did not meet expectation: expected=Succeed actual=TimeOut (killed due to timeout)."
+				__cat_test_result="FAILURE"
+				__cat_test_exit_code=$rc
+				xmlLog $tcoutdat
 				continue
 			elif [[ $rc > 0 && $tcvcode == "SUCCEED" ]]; then
 				printf " *** X ***"
 				let 'tcfailcnt += 1'
 				let 'tcfexeccnt += 1'
 				printf "\n[$prog: err]: failed to execute ${tctarget}\n"
+				__cat_test_result_explanation="${tctarget} did not meet expectation: expected=Succeed actual=FailRun (execution failed)."
+				__cat_test_result="FAILURE"
+				__cat_test_exit_code=$rc
+				xmlLog $tcoutdat
 				continue
 			elif [[ $rc == 0 && $tcvcode == "FAIL_RUN" ]]; then
 				printf " *** X ***"
 				let 'tcfailcnt += 1'
 				let 'tcfvcodecnt += 1'
 				printf "\n[$prog: err]: invalid validation code ${tcvcode}\n"
+				__cat_test_result_explanation="${tctarget} did not meet expectation: expected=MustFailRun actual=Succeed (invalid vaditation code)."
+				__cat_test_result="FAILURE"
+				__cat_test_exit_code=42
+				xmlLog $tcoutdat
 				continue
 			elif [[ $rc > 128 && $tcvcode == "FAIL_RUN" ]]; then
 				printf " *** X ***"
@@ -690,23 +817,39 @@ function main {
 				let 'tcftoutcnt += 1'
 				let 'tcfexeccnt += 1'
 				printf "\n[$prog: err]: ${tctarget} is killed due to timeout\n"
+				__cat_test_result_explanation="${tctarget} did not meet expectation: expected=MustFailRun actual=TimeOut (killed due to timeout)."
+				__cat_test_result="FAILURE"
+				__cat_test_exit_code=$rc
+				xmlLog $tcoutdat
 				continue
 			elif [[ $rc > 0 && $tcvcode == "FAIL_RUN" ]]; then
 				printf " *** Y ***"
 				let 'tcfexeccnt += 1'
 				let 'tcpasscnt += 1'
+				__cat_test_result_explanation="${tctarget} met expectation: MustFailRun."
+				__cat_test_result="SUCCESS"
+				__cat_test_exit_code=0
+				xmlLog $tcoutdat
 				continue
 			elif [[ $rc == 0 && $tcvcode == "FAIL_TIMEOUT" ]]; then
 				printf " *** X ***"
 				let 'tcfailcnt += 1'
 				let 'tcfvcodecnt += 1'
 				printf "\n[$prog: err]: invalid validation code ${tcvcode}\n"
+				__cat_test_result_explanation="${tctarget} did not meet expectation: expected=MustFailTimeOut actual=Succeed (invalid validation code)."
+				__cat_test_result="FAILURE"
+				__cat_test_exit_code=42
+				xmlLog $tcoutdat
 				continue
 			elif [[ $rc > 128 && $tcvcode == "FAIL_TIMEOUT" ]]; then
 				printf " *** Y ***"
 				let 'tcftoutcnt += 1'
 				let 'tcfexeccnt += 1'
 				let 'tcpasscnt += 1'
+				__cat_test_result_explanation="${tctarget} met expectation: MustFailTimeOut."
+				__cat_test_result="SUCCESS"
+				__cat_test_exit_code=0
+				xmlLog $tcoutdat
 				continue
 			elif [[ $rc > 0 && $tcvcode == "FAIL_TIMEOUT" ]]; then
 				printf " *** X ***"
@@ -714,10 +857,17 @@ function main {
 				let 'tcftoutcnt += 1'
 				let 'tcfexeccnt += 1'
 				printf "\n[$prog: err]: failed to execute ${tctarget}\n"
+				__cat_test_result_explanation="${tctarget} did not meet expectation: expected=MustFailTimeOut actual=FailRun (execution failed)."
+				__cat_test_result="FAILURE"
+				__cat_test_exit_code=$rc
+				xmlLog $tcoutdat
 				continue
 			fi
 		fi
 	done
+	if [[ "${__cat_opened_group}" != "invalid" ]]; then
+		printf "</group>\n" >> $TLOGF
+	fi
 
 	# prepare the report
 	# simple summary for the moment
@@ -748,7 +898,26 @@ function main {
 	printf "\n======================================================================\n\n" >> ${tctmpreport}
 }
 
+__cat_opened_group="invalid"
+__cat_current_group=""
+__cat_test_name=""
+__cat_test_x10c_command=""
+__cat_test_x10_command=""
+__cat_test_parameters=""
+__cat_test_exit_code=""
+__cat_test_start_time=""
+__cat_test_end_time=""
+__cat_test_duration=""
+__cat_test_result=""
+__cat_test_result_explanation=""
+__cat_test_output=""
+__cat_test_x10c_sourcepath=""
+__cat_test_x10c_classpath=""
+__cat_test_x10c_directory=""
+__cat_test_x10_classpath=""
+__cat_test_x10_timeout=""
+
 init "$@"
 writeLogHead > ${tctmprhlog} 2>${tctmpelog}
 main > ${tctmprlog} 2>>${tctmpelog}
-cleanUpExit 0
+cleanUpExitHarness 0
