WIP XTENLANG-3176. use "-Djava.class.path=XYZ" instead of "-classpath XYZ" so that it can be passed to JNI_CreateJavaVM.
git-svn-id: svn://svn.code.sf.net/p/x10/code/trunk@24988 a326200e-df2c-42e0-81fa-597e909af41d

diff --git a/x10.dist/bin/x10.in b/x10.dist/bin/x10.in
--- a/x10.dist/bin/x10.in
+++ b/x10.dist/bin/x10.in
@@ -38,6 +38,10 @@ while [ -n "$1" ]; do
                  echo >&2 "Error: Cannot reset java.library.path, use -libpath instead"
                  exit 1
              fi
+             if [[ "${1##-D}" = java.class.path=* ]]; then
+                 echo >&2 "Error: Cannot reset java.class.path, use -classpath instead"
+                 exit 1
+             fi
              # TODO: add tests for more system properties above
              defs="${defs} $1";;
         -classpath|-cp)
@@ -172,7 +176,7 @@ fi
 
 # TODO: executable jar
 # Note: use bootstrap class path instead of user class path to make it visible from jar file
-java_args=("-Djava.library.path=$externpath" -classpath "$classpath" "${java_args[@]}")
+java_args=("-Djava.library.path=$externpath" "-Djava.class.path=$classpath" "${java_args[@]}")
 #java_args=("-Djava.library.path=$externpath" "-Xbootclasspath/a:$classpath" "${java_args[@]}")
 
 if [ -z "$noassert" ]; then
