merging trunk changes from r15363 to r15738 removed dependency on polyglot imported com.ibm.wala.cast.java.polyglot into com.ibm.wala.cast.x10
git-svn-id: svn://svn.code.sf.net/p/x10/code/branches@15758 a326200e-df2c-42e0-81fa-597e909af41d

diff --git a/scalable-finish/x10.tests/bin/xtestScriptCT++ b/scalable-finish/x10.tests/bin/xtestScriptCT++
--- a/scalable-finish/x10.tests/bin/xtestScriptCT++
+++ b/scalable-finish/x10.tests/bin/xtestScriptCT++
@@ -337,10 +337,12 @@ prog=x10c++th
 # platform independent abstraction for certain commands
 EGREP=egrep
 egrep --version 2>/dev/null 1>/dev/null
-if [[ $? == 0 && $(uname -s) != Sun* ]]; then
+if [[ $? == 0 && $(uname -s) != Sun* && $(uname -s) != CYGWIN* ]]; then
 	EGREP="egrep -E"
 fi
+if [[ -z "$MAILCMD" ]]; then
 MAILCMD=mail
+fi
 if [[ $(uname -s) == Sun* ]]; then
 	MAILCMD=mailx
 fi
@@ -609,6 +611,8 @@ function main {
 	    X10CPP="$X10CPP -x10rt pgas_sockets"
 	elif [[ "$(uname -s)" == "SunOS" && "$(uname -p)" == "sparc" ]]; then
 	    X10CPP="$X10CPP -x10rt pgas_sockets"
+	elif [[ "$(uname -s)" == CYGWIN* && "$(uname -m)" == "i686" ]]; then
+	    X10CPP="$X10CPP -x10rt pgas_sockets"
 	fi
 
 	if [[ ! -f $X10_HOME/x10.dist/include/x10rt.h ]]; then
@@ -687,7 +691,11 @@ function main {
 		__cat_test_x10c_sourcepath="$tcroot"
 		__cat_test_x10c_classpath="${EXTRA_CLASSPATH}"
 		__cat_test_x10c_directory="$testDir"
+if [[ "$(uname -s)" == CYGWIN* ]]; then
+		comp_cmd="${X10CPP} $extra_opts $X10CPP_EXTRA_OPTS -t -v -report postcompile=1 -CHECK_INVARIANTS=true -MAIN_CLASS=$tctarget -sourcepath \"$(cygpath -am $tcroot)\" -sourcepath \"$(cygpath -am $X10_HOME/x10.dist/samples)\"  -sourcepath \"$(cygpath -am $X10_HOME/x10.dist/samples/tutorial)\" -sourcepath \"$(cygpath -am $X10_HOME/x10.dist/samples/CUDA)\" -d \"$(cygpath -am $tcroot)\" $tc $extendList \"$(cygpath -am ${X10TEST_PATH}/x10lib/harness/x10Test.x10)\""
+else
 		comp_cmd="${X10CPP} $extra_opts $X10CPP_EXTRA_OPTS -t -v -report postcompile=1 -CHECK_INVARIANTS=true -MAIN_CLASS=$tctarget -sourcepath $tcroot -sourcepath $X10_HOME/x10.dist/samples -sourcepath $X10_HOME/x10.dist/samples/tutorial -sourcepath $X10_HOME/x10.dist/samples/CUDA -d $tcroot $tc $extendList ${X10TEST_PATH}/x10lib/harness/x10Test.x10"
+fi
 		tccompdat=${tcroot}/${tctarget}.comp
 		printf "\n****** $tDir $className ******\n\n" >> $tccompdat
 
@@ -698,12 +706,22 @@ function main {
 		cat ${tccompdat} 1>&2
 		if [[ $rc != 0 && "$tcvcode" == "FAIL_COMPILE" ]]; then
 			let 'tcfcompcnt += 1'
-			let 'tcpasscnt += 1'
-			printf " *** Y ***"
-			__cat_test_result_explanation="${className} met expectation: MustFailCompile."
-			__cat_test_result="SUCCESS"
 			__cat_test_exit_code=$rc
-			printf "\n****** $tDir $className succeeded.\n" >> $tccompdat
+            ${EGREP} "Exception in thread" $tccompdat >/dev/null 2>&1
+            if [[ $? == 0 ]]; then
+                printf " *** X ***"
+                let 'tcfailcnt += 1'
+                printf "\n[$prog: err]: compile time exception for ${className}\n"
+                __cat_test_result_explanation="${className} did not meet expectation: expected=MustFailCompile actual=FailCompileWithException (exception in thread main)."
+                __cat_test_result="FAILURE"
+                printf "\n****** $tDir $className failed: compile time exception\n" >> $tccompdat
+            else
+			    printf " *** Y ***"
+			    let 'tcpasscnt += 1'
+			    __cat_test_result_explanation="${className} met expectation: MustFailCompile."
+			    __cat_test_result="SUCCESS"
+			    printf "\n****** $tDir $className succeeded.\n" >> $tccompdat
+            fi
 			xmlLog $tccompdat
 			continue
 		elif [[ $rc == 0 && "$tcvcode" == "FAIL_COMPILE" ]]; then
@@ -762,7 +780,11 @@ do
 done
 			fi
 fi
+if [[ "$(uname -s)" == CYGWIN* ]]; then
+			run_cmd="/usr/bin/time -p mpirun -np $my_nplaces ./${tctarget}.exe"
+else
 			run_cmd="/usr/bin/time -p mpirun -np $my_nplaces ./${tctarget}"
+fi
 			printf "\n${run_cmd}\n" >> $tcoutdat
 		fi
 
